### ISSUE TITLE
Add jvm option siteURL to install script

### ISSUE THREAD

**Issue by jmjamison** [ucla-data-archive/dataverse-ansible#25]

**Comment by jmjamison** [comment]
The jvm option has to be added to the install script so that the access request link that the administrator receives has to have the 8080 port number.   

<jvm-options>-Ddataverse.fqdn=dataverse.example.edu</jvm-options>
<jvm-options>-Ddataverse.siteUrl=http://${dataverse.fqdn}:8080</jvm-options>

**Comment by jt14den** [comment]
create a task that kicks off after every runs to add these values to the site

**Comment by jmjamison** [comment]
I have this working and tested with Vagrant.
TASK: [dataverse | add jvm option siteURL] ************************************ 
changed: [default] => {"changed": true, "cmd": ["nohup", "/usr/local/glassfish4/bin/asadmin", "create-jvm-options", "-Ddataverse\\.siteUrl=http\\://${dataverse.fqdn}\\:8080"], "delta": "0:00:00.753904", "end": "2018-09-06 14:51:23.474636", "rc": 0, "start": "2018-09-06 14:51:22.720732", "stderr": "", "stdout": "Created 1 option(s)\nCommand create-jvm-options executed successfully.", "warnings": []}

Problem I was running into was how bash interpreted the punctuation and single vs double quotes.:  '-Ddataverse\.siteUrl=http\://${dataverse.fqdn}\:8080'

**Comment by jmjamison** [comment]
So, it's been tested with Vagrant but not on a RHEL build

**Comment by jmjamison** [comment]
Tested on an AWS server and the line was added correctly.
