### ISSUE TITLE
Shibboleth integration

### ISSUE THREAD

**Issue by jmjamison** [ucla-data-archive/dataverse-ansible#28]
Need to send IAMS cert and shibb2.xml

**Comment by jmjamison** [comment]
We need to select attributes.

[iamucla-AvailableEDAttributes-270818-1457-38420.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5988a77b7d1051001fe82b85/125516c66e82c728ace21e0d46e1959736818fa8c2c8a942ad51f196254302570810b7397987f63cba513653585f46ad49455e40f9fe9428aeb23e70984019ad93320521957903a6aa874db902bb21de4dd6b5e88c1e94e83d24b5d9dd473c1f060a95ed1f64fecd149501bc1ea35f5fb6123169e7733579439419772c6e6520a9ee92.pdf)
[iamucla-AvailableShibAttributes-270818-1457-38418.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5988a77b7d1051001fe82b85/125516c66e82c728ace21e0d46e1959736818fa8c2c8a942ad51f1962543147b2006823f6497ea2aaa567e12425d49ac49595759fdfd8c2cbbb534748b5419f1c32d1d2b9c6842e8aa880dba53bc238a4ed0b4ef8918c6ba6925e78add1d6c1607198aed4127e2c8159c07ab12ab1817b6192461e47c377944911a752b69662facf8db44ca.pdf)

**Comment by jmjamison** [comment]
Also here is a link to the "planning guide": 
https://spaces.ais.ucla.edu/display/iamuclabetadocs/ShibPlanning-GetData

**Comment by jt14den** [comment]
meeting with dave shepherd on Friday. We can start plannign

**Comment by jt14den** [comment]
communication with registrar about ferpa and uc data policy.

**Comment by jmjamison** [comment]
Installed our trackingID on test.dataverse.ucla.edu.  
Started working notes: <https://docs.google.com/document/d/1EYRf9hfIsbU2WazamMJ9Ut381897V-X1nfJn4eZVeRU/edit>

Have questions for Sharon Schaffer who is out this week regarding the 2 analytic tags - ours and ucla cumulative
