### ISSUE TITLE
Security: blocking API endpoints

### ISSUE THREAD

**Issue by jmjamison** [ucla-data-archive/dataverse-ansible#37]
See:  <http://guides.dataverse.org/en/latest/installation/config.html#blocking-api-endpoints>

**Comment by jt14den** [comment]
we are wait on shibboleth, but will work on how to do this

Questions: Which method do we need to employ to block api endpoint? 

see: http://guides.dataverse.org/en/latest/installation/config.html

**Comment by jmjamison** [comment]
Notes: <https://drive.google.com/open?id=12h2ICssd0WC6666jv-rYPZu26V0NXLbJJeO4qDLoDOA>

Following the dataverse install/configuration directions: 
1)  set blocked api policy to allow localhost-only
2) blocked api endpoints: admin and built-in user
