### ISSUE TITLE
Security: privacy considreations

### ISSUE THREAD

**Issue by jmjamison** [ucla-data-archive/dataverse-ansible#39]
See: <http://guides.dataverse.org/en/latest/installation/config.html#id33>

"Out of the box, Dataverse will list email addresses of the “contacts” for datasets when users visit a dataset page and click the “Export Metadata” button. If you prefer to exclude email addresses of dataset contacts from metadata export, set :ExcludeEmailFromExport to true."

**Comment by jt14den** [comment]
Preference is to leave email associated with dataset b/c end-users might need to contact data producers about dataset. Unless there's some campus privacy policy, we will leave email associated with data.
