### ISSUE TITLE
dataverse smtp settings

### ISSUE THREAD

**Issue by jmjamison** [ucla-data-archive/dataverse-ansible#40]
Currently using my google smtp settings for dataverse admin email notifications.

Need to get non-personal smtp setup

**Comment by jmjamison** [comment]
The jira ticket: https://jira.library.ucla.edu/browse/LX-524

**Comment by jt14den** [comment]
Need to setup with google apps - datascience+dvn@ucla.edu

**Comment by jmjamison** [comment]
Having some difficulty getting the app password.  Error (below): "setting you are looking for is not available for your account".   Sent a question to the bol help-desk, waiting for reply.

![googleScreenshot.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5988a77b7d1051001fe82b85/125516c66e82c728ace21e0d46ef9b95248e869a8cfbba46aa4ef89b3d046b313916ac217586f76ae5002e03595c4fad145a0c47a8ffdb7fa6b63d22d80e03efd06e4d68d47f40f2ecdd42e64bef62994597b7bb804dc5ec3e20e6838d4e3e1604109bb2.png)

**Comment by jt14den** [comment]
@jmjamison is going to open jira ticket to get outlook ad - dataverse@library.ucla.edu for smtp

**Comment by jmjamison** [comment]
Working with David Lakatta to get lib_dataverse@library.ucla.edu to work for smtp. Not sending mail. Back to picking through java error messages.

**Comment by jmjamison** [comment]
Problem fixed with Dave Lakatta's help.
