### ISSUE TITLE
ca cert for https on server

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#42]
https://jira.library.ucla.edu/browse/LX-525?

**Comment by jmjamison** [comment]
Certificates installed on test.dataverse.ucla.edu.

Directions are somewhat conflicting but it appears that SELinux has to be set to passive (or disabled).  I have it set to passive.  

Used the certificate files generated by Charlie Chen.  (see <https://jira.library.ucla.edu/browse/LX-525>)

**Comment by jmjamison** [comment]
Added certificates to dataverse.ucla.edu. 
Again, set SELinux to permissive
