### ISSUE TITLE
Enforce Strong Passwords for User Accounts Dataverse only stores passwords

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#45]
@jmmaison and @jt14den will research this and implications

**Comment by jmjamison** [comment]
Working a a list of characteristics, in team drive: <https://drive.google.com/open?id=1SdqTz-EvdhadPAiYPRRRXehFb_SDOm368hhx7UPng8g>

**Comment by jmjamison** [comment]
For both test and production:
1) default minimum length of password:  16
2) number of consecutive digits allowed: 4
3) character rules: 1 uppercase, 1 lowercase, 1 special character, 1 digit
4) number of characteristics (matches character rules): 4
5) good strentth
