### ISSUE TITLE
sub dataverse policy and structure

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#46]
look at other dataverse institutions and see how they provide help and policy for sub-dataverses, conventions, etc

**Comment by jt14den** [comment]
We need to look back at our comparative analysis and see if there is any documentation we can use.

**Comment by jmjamison** [comment]
Started a google doc in dataverse/dataverse-working-notes/roles-permissions-subdataverses.
https://drive.google.com/open?id=177p7ZtsHOK186eYsd-4INcTL-3YxjVHTG3C76JS8WXk
