### ISSUE TITLE
look into cross region replication for S3

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#49]
we should replicate our data on other regions on a schedule.

**Comment by jmjamison** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/crr.html

**Comment by jmjamison** [comment]
Created a bucket for replication in US-East-1 (N. Virginia).   One of the cheapest regions and on an opposite coast.   Still going through the documentation.

**Comment by jmjamison** [comment]
Enabled cross-region replication. Made a specific folder in data-science-center/data-infrastructure-repo/dataverse/s3-cross-replication-notes,   doc:  https://drive.google.com/open?id=1aF-x67hO9b9-joPDISec813jvfTkrfrA00CJJ3Xkl0E

**Comment by jmjamison** [comment]
In order to check out my cross rep configuration I've put in a jira ticket LX-638 so someone with aws experience can do a quick checkover.
