### ISSUE TITLE
rclone for backing up to box

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#50]
- [ ] set up rclone headless on dvn machine on a cron to synch to datasci box 
- [ ] figure the right rclone commands (and flags) to run to synch data down to our datasci box account
- [ ] set up rclone to run on chron on test instance
- [ ] test it and make sure it works (chron) checksum for data it copies
- [ ] figure our how to connect and save from s3

**Comment by jmjamison** [comment]
Some documentation: <https://rclone.org/s3/>

**Comment by jmjamison** [comment]
As a start I've installed rclone on my desktop and synced to box.   Set up a cron script but it didn't run so I have to go over the crontab documentation

**Comment by jmjamison** [comment]
Installed rclone on the test system

**Comment by jmjamison** [comment]
rclone on both test and production.
Notes: https://drive.google.com/open?id=1r5RI4cxOrw9lLlxj1sOm60_T3iB6NugXzutC8M1Pcwk
