### ISSUE TITLE
draw architecture of dvn

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#51]
We should scope out what the sub-dataverse looks like for the data archive - should it be a dvn below `ucla dataverse` as ucla data archive and then below that contain 'ssda', etc.

**Comment by jmjamison** [comment]
I don't want to bury ssda too deep.  Personally I'd prefer ssda as separate from ucla data archive.

**Comment by jt14den** [comment]
We need to play with the how the sub-dataverses work and how the hierarchies work.
