### ISSUE TITLE
switch from ezid test account to ucla-dvn

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#55]
before we go live we need to use the real dvn account

**Comment by jt14den** [comment]
Only for production.

**Comment by jmjamison** [comment]
Updated userid, password.  Still need to test.

**Comment by jmjamison** [comment]
I was checking over how I set up production EZID/DOI, made some corrections and still have questions about the "shoulder" and the "authority".  If I can't solve this on my on by friday I'm going  ask someone at cdl

**Comment by jmjamison** [comment]
Also, when updating account and password for EZID/DOI I  replaced the password they gave us with something longer and more difficult. Documented in the 'doi notes' doc in our team drive

**Comment by jt14den** [comment]
@jmjamison is going to test in prod with her dataset to confirm the prod doi work.
