### ISSUE TITLE
retrieve ORCID api keys for DVN

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#56]
Users can use ORCID for authentication and connect to ORCID 

- [x] Request orcid api key
- [x] apply to dataverse settings
- [ ] test orcid connection

**Comment by jt14den** [comment]
need to follow up with orcid to get api key so we can set in dvn

**Comment by jt14den** [comment]
added key to gdrive.

**Comment by jmjamison** [comment]
Getting incorrect 'return uri' errors.  I've emailed a question to orcid support.

**Comment by jmjamison** [comment]
Issue with uri errors fixed.   It's now possible to log into production with ORCID. BUT dataverse UI asks to convert to ORCID login or make new account.  It doesn't like like one can log in multiple ways.  I have to verify this.

test.dataverse is still using ORCID sandbox.

**Comment by jt14den** [comment]
@jt14den look at how ORCID is configured with existing accounts via shib
