### ISSUE TITLE
shibboleth in production

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#61]
get shib working in production

**Comment by jt14den** [comment]
[ ] Move shibboleth2.xml, ucla-idp-metadata.xml from test, changed entity id domain, etc.
[ ] Step through shib set up instruction with appache, shibd, etc. so they mirror test 
[ ] Test

**Comment by jt14den** [comment]
After moving shibboleth2.xml and ucla-idp-metadata.xml and making changes from test, still throwing error "Problem with Identity Provider – The SAML assertion for "eppn" was null. Please contact support." - need to debug

**Comment by jmjamison** [comment]
I believe that I have this fixed.  Based on the shibboleth error log I believe that it was the attribute-map.xml file.  I've saved what is currently there and copied over the working attribute-map.xml file from test.dataverse.  We can compare them in detail when you get back.  

But for the moment it seems to be working.  Converted my login to Institutional login.

**Comment by jmjamison** [comment]
Louise just created on account on production, shibboleth seems to be working.
