### ISSUE TITLE
Comparative analysis of other schools

### ISSUE THREAD

**Issue by jt14den** [ucla-data-archive/dataverse-ansible#7]
Take notes: 
1. is the service available for only the institutional members
2. can undergrads use
3. documentation and training?
4. Documentation of backup/preservation practices
5. any certification?
6. Grab the Terms of Service 
7. dataverse policy (getting a separate dvn)

Attach notes here. 

- [x] Texas data repository: https://data.tdl.org/
- [x] Harvard dataverse
- [ ] QDR https://data.qdr.syr.edu/
- [x] UAL https://dataverse.library.ualberta.ca/
- [x] UNC dataverse https://dataverse.unc.edu/
- [x] ADA Dataverse https://dataverse.ada.edu.au/
- [x] Scholars lab https://dataverse.scholarsportal.info/

**Comment by jmjamison** [comment]
https://drive.google.com/open?id=14Z9eRqhQTEputjO1WSO-ukX7hfFjwwgQqLQDGzbCVYc

**Comment by jt14den** [comment]
We should finish this and add new questions. 

Document with comparison here: https://docs.google.com/document/d/14Z9eRqhQTEputjO1WSO-ukX7hfFjwwgQqLQDGzbCVYc/edit

**Comment by jt14den** [comment]
have email out to texas about their setup -- need to remind them

**Comment by jt14den** [comment]
Never heard back from TDR, but can follow up

**Comment by jt14den** [comment]
reopened this ticket and added @leighphan so can look at other instances of dvn.
